### Loading torch


In [1]:
import torch
print(torch.__version__)

1.8.0


 ### Initializing tensor in the torch
* Initialize the tensor, datatype and the device.
 


In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor =  torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [14]:
print(f'tensor data:{my_tensor}, tensor data type: {my_tensor.dtype}, \
tensor device: {my_tensor.device}, tensor shape: {my_tensor.shape}, tensor_grad: {my_tensor.requires_grad}')

tensor data:tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True), tensor data type: torch.float32, tensor device: cpu, tensor shape: torch.Size([2, 3]), tensor_grad: True


In [15]:
### create an empty tensor
x1=torch.empty(size=(3,3))
x2=torch.zeros((3,3))
x3 = torch.rand((3,3))
x4 = torch.ones((3,3))
x5 = torch.eye(5,5)
print (x1,x2,x3,x4,x5)

tensor([[ 0.0000e+00, -4.6566e-10,  4.0165e-27],
        [-2.5244e-29,  9.8091e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[0.2868, 0.8714, 0.5598],
        [0.6663, 0.0018, 0.7475],
        [0.5487, 0.5802, 0.7217]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [17]:
print(torch.arange(start=0,end=10,step=1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
print(torch.linspace(start=0.1,end=1,steps=10))

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [20]:
y = torch.empty(size=(1,5)).normal_(mean=0,std=1)
print(y)

tensor([[-0.8473, -0.4618,  0.7690, -0.9495, -1.4119]])


In [22]:
y = torch.empty(size=(1,5)).uniform_(0,1)
print(y)

tensor([[0.9539, 0.5561, 0.6378, 0.3105, 0.4520]])


In [24]:
print(torch.diag(torch.ones(3)))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [27]:
tensor = torch.arange(4); print(tensor)
print(tensor.bool())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])


In [28]:
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [35]:
print(tensor.double())
print(tensor.float())
print(tensor.half())
print(tensor.long())

tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0, 1, 2, 3])


In [36]:
import numpy as np

In [37]:
np_array = np.zeros((5,5));print(np_array)
tensor = torch.from_numpy(np_array);print(tensor)
ttensor = tensor.numpy(); print(ttensor)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Tensor math and operations


In [87]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z=torch.empty(3)
torch.add(x,y,out=z)
print(z)

tensor([10., 10., 10.])


In [40]:
z2=torch.add(x,y)
z3=x+y
print(z2,z3)


tensor([10, 10, 10]) tensor([10, 10, 10])


In [42]:
z = x-y;print(z)

tensor([-8, -6, -4])


In [44]:
z=torch.true_divide(x,y);print(z)

tensor([0.1111, 0.2500, 0.4286])


In [49]:
t = torch.zeros(3)
### inplace operator_
t.add_(x)
print(t)
t += x
print(t)


tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [50]:
z=x.pow(2); print(z)

tensor([1, 4, 9])


In [51]:
z = x**2 ; print(z)

tensor([1, 4, 9])


In [54]:
z=x>0;print(z)
z=x<0;print(z)

tensor([True, True, True])
tensor([False, False, False])


In [55]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) ;print(x3)
x3 = x1.mm(x2) ; print(x3)

tensor([[1.3367, 1.2165, 1.0856],
        [1.3425, 1.2957, 1.3433]])
tensor([[1.3367, 1.2165, 1.0856],
        [1.3425, 1.2957, 1.3433]])


In [59]:
### matrix exponent
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(2))

tensor([[2.2931, 2.0380, 2.3565, 2.1524, 1.6194],
        [2.0388, 1.8277, 2.0386, 2.2302, 1.6827],
        [2.3910, 2.0460, 1.7564, 1.8534, 1.7238],
        [1.0098, 0.9814, 1.2913, 0.5999, 0.4807],
        [2.3678, 2.0806, 2.2203, 1.9816, 1.7717]])


In [60]:
z=x* y # element wise multiplication
print(z)

tensor([ 9, 16, 21])


In [61]:
## dot product
z=torch.dot(x,y);print(z)

tensor(46)


In [65]:
# batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch,n,m))
tensor2 = torch.rand((batch,m,p))

out_bbm = torch.bmm(tensor1,tensor2)
print(out_bbm.shape)

torch.Size([32, 10, 30])


In [69]:
### example of broadcasting creating 5 identical copies of x2 and subtracting those 5 copies from x1
x1 = torch.rand((5,5));print(x1)
x2 = torch.rand((1,5));print(x2)
z = x1 - x2; print(z)
z = x1**x2;print(z)

tensor([[0.5072, 0.1631, 0.8815, 0.1986, 0.5324],
        [0.5083, 0.9506, 0.0393, 0.1160, 0.3408],
        [0.2207, 0.3236, 0.9197, 0.1685, 0.8108],
        [0.6739, 0.2016, 0.9672, 0.0101, 0.8861],
        [0.2599, 0.5985, 0.3868, 0.5664, 0.3799]])
tensor([[0.0786, 0.2577, 0.2768, 0.1090, 0.9417]])
tensor([[ 0.4286, -0.0946,  0.6047,  0.0896, -0.4093],
        [ 0.4297,  0.6929, -0.2375,  0.0070, -0.6009],
        [ 0.1421,  0.0659,  0.6429,  0.0596, -0.1309],
        [ 0.5954, -0.0561,  0.6904, -0.0989, -0.0556],
        [ 0.1813,  0.3408,  0.1100,  0.4575, -0.5618]])
tensor([[0.9480, 0.6267, 0.9657, 0.8385, 0.5523],
        [0.9482, 0.9870, 0.4082, 0.7907, 0.3628],
        [0.8880, 0.7477, 0.9771, 0.8236, 0.8208],
        [0.9695, 0.6618, 0.9908, 0.6060, 0.8924],
        [0.8995, 0.8761, 0.7688, 0.9399, 0.4019]])


In [74]:
### sum of tensors
print(x)
sum_x = torch.sum(x,dim=0);print(sum_x)
values,indices = torch.max(x,dim=0);print(values,indices)
values,indices = torch.min(x,dim=0);print(values,indices)
print( torch.abs(x))

### finding minimum and maximum
print(torch.argmax(x,dim=0))
print(torch.argmin(x,dim=0))

tensor([1, 2, 3])
tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([1, 2, 3])
tensor(2)
tensor(0)


In [76]:
### mean
print(torch.mean(x.float(),dim=0))

### element wise comparison
print(torch.eq(x,y))

tensor(2.)
tensor([False, False, False])


In [77]:
print(torch.sort(y,dim=0,descending=False))

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))


In [88]:
### clamp: check all elements of an array set the negative values to min and maximum to max
z=torch.clamp(x,min=1,max=2);print(z)

## check if any element is tru
x2 = torch.tensor([1,0,1,1,1],dtype=torch.bool);print(torch.any(x2))

## check it all elements are true
print(torch.all(x2))

tensor([1, 2, 2])
tensor(True)
tensor(False)


In [89]:
print(x.max(dim=0))
print(x.min(dim=0))



torch.return_types.max(
values=tensor(3),
indices=tensor(2))
torch.return_types.min(
values=tensor(1),
indices=tensor(0))


In [94]:
### tensor indexing
batch_size = 10
features = 25
x = torch.rand((batch_size,features))
print(x[0].shape)
print(x[0,:])
print(x[:,0])
print(x[:,0].shape)

torch.Size([25])
tensor([0.5729, 0.3780, 0.1514, 0.4043, 0.8214, 0.3911, 0.5275, 0.8348, 0.9478,
        0.7149, 0.4204, 0.0778, 0.0620, 0.7570, 0.1771, 0.0498, 0.8086, 0.4051,
        0.2753, 0.1673, 0.0665, 0.4600, 0.1052, 0.0906, 0.1196])
tensor([0.5729, 0.4107, 0.3936, 0.4297, 0.0303, 0.9073, 0.1505, 0.1121, 0.0721,
        0.1095])
torch.Size([10])


In [95]:
print(x[2,0:10])

tensor([0.3936, 0.0167, 0.8429, 0.0666, 0.6801, 0.7918, 0.0690, 0.4232, 0.7355,
        0.5154])


In [96]:
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [97]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols])

tensor([0.1982, 0.3963])


In [100]:
x = torch.arange(10)
print(x[(x<2)  | (x>8)])
print(x[(x<2)   & (x>8)])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)


In [101]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [102]:
print(x[x.remainder(2)==1])

tensor([1, 3, 5, 7, 9])


In [111]:
### if condition that checks the tensor entries and modifies the contents of the tensor

print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,2,3,1,1,2,3,5]).unique())
print(x.ndimension())
print(torch.rand(5,5).ndimension())
print(torch.rand(5,5).numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 5])
1
2
25


In [113]:
### reshaping a tensor
x = torch.arange(9)
x2 = x.view(3,3) ## view act on contagious memory
x3 = x.reshape(3,3) ## doesn't matter
print(x,x2,x3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [121]:
y = x2.t();print(y)

x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1).shape)

tensor([[0.0909, 0.2502],
        [0.8392, 0.8112],
        [0.2668, 0.0381],
        [0.6799, 0.6519],
        [0.1984, 0.9580]])
torch.Size([4, 5])
torch.Size([2, 10])


In [125]:
z = x1.view(-1);print(z,z.shape)
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch,-1)
print(z.shape)

tensor([0.4258, 0.1934, 0.1216, 0.3465, 0.1978, 0.2556, 0.4634, 0.4987, 0.0815,
        0.2064]) torch.Size([10])
torch.Size([64, 10])


In [126]:
z = x.permute(0,2,1);print(z.shape)

torch.Size([64, 5, 2])


In [128]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


# Creating a neural network in pytorch


In [129]:
import torch
import torch.nn as nn ## neural network modules,architecture
import torch.optim as optim ## optimizers 
import torch.nn.functional as F ## activation fns
from torch.utils.data import DataLoader ## to load and use dataset
import torchvision.datasets as datasets
import torchvision.transforms as transforms ## transformations for our datasets



In [130]:
### defining the NN class that inherits from nn.Module

class NN(nn.Module):
    def __init__(self,input_size,num_classes):
        super(NN,self).__init__()
        self.fc1 = nn.Linear(input_size,50)
        self.fc2 = nn.Linear(50,num_classes)
    
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [131]:
## create an object
model = NN(784,10)
## trial data
x = torch.randn(64,784)

print(model(x).shape)

torch.Size([64, 10])


In [133]:
## set the hyperparameter
input_size = 784
num_classes = 10
learning_rate = 0.001
batch_size = 64
num_epochs = 5

In [134]:
### load data
train_dataset = datasets.MNIST(root='dataset/',train=True,transform=transforms.ToTensor(),download=True)
train_loader = DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)

test_dataset = datasets.MNIST(root='dataset/',train=False,transform=transforms.ToTensor(),download=True)
test_loader = DataLoader(dataset=test_dataset,batch_size=batch_size,shuffle=True)

In [135]:
## initialize the network

model = NN(input_size=input_size,num_classes=num_classes).to(device)

In [136]:
## loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

In [140]:
## train network
for epoch in range(1):
    for batch_idx,(data,targets) in enumerate(train_loader):
        ## get data to cuda
        data = data.to(device=device)
        targets = targets.to(device=device)
        #print(data)
        print(targets)
        # get to correct shape

        data = data.reshape(data.shape[0],-1)


        # forward
        scores = model(data)
        loss = criterion(scores,targets)
        
        ## backward
        ## set grad zero for each batch
        optimizer.zero_grad()
        loss.backward()
        
        ## gradient descent
        optimizer.step()
        
        
def check_accuracy(loader,model):
    num_correct = 0
    num_samples = 0
    model.eval()
    
    ## no grad computation for this calculation
    with torch.no_grad():
        for x,y in loader:
            x=x.to(device=device)
            y=y.to(device=device)
            x = x.reshape(x.shape[0],-1)
            
            scores = model(x)
            _,predictions = scores.max(1)
            
            num_correct+= (predictions==y).sum()
            num_samples+=predictions.size(0)
            
        print(num_correct/num_samples)
    model.train()


check_accuracy(train_loader,model)
check_accuracy(test_loader,model)

tensor([2, 3, 4, 9, 1, 9, 1, 1, 5, 6, 5, 0, 8, 6, 8, 6, 3, 2, 9, 4, 8, 7, 4, 4,
        5, 2, 6, 5, 0, 9, 1, 7, 1, 2, 8, 9, 0, 0, 1, 5, 3, 6, 1, 0, 5, 1, 0, 6,
        8, 2, 4, 9, 8, 6, 9, 7, 0, 8, 8, 7, 2, 2, 4, 4])
tensor([1, 8, 4, 1, 1, 8, 8, 9, 5, 9, 4, 1, 9, 9, 6, 3, 7, 7, 1, 6, 8, 8, 5, 0,
        5, 0, 3, 5, 9, 1, 8, 6, 8, 7, 4, 9, 2, 7, 9, 2, 9, 1, 7, 1, 0, 7, 1, 9,
        5, 7, 9, 0, 4, 4, 7, 6, 0, 6, 7, 3, 1, 3, 2, 2])
tensor([8, 2, 7, 4, 6, 2, 8, 8, 6, 2, 1, 6, 7, 4, 4, 8, 8, 6, 8, 5, 4, 9, 3, 2,
        7, 2, 0, 4, 7, 2, 1, 2, 3, 5, 2, 0, 0, 4, 5, 5, 6, 3, 1, 4, 0, 4, 3, 9,
        0, 7, 3, 1, 0, 2, 7, 2, 1, 4, 4, 9, 9, 1, 6, 6])
tensor([6, 6, 4, 8, 5, 4, 4, 8, 5, 8, 5, 8, 4, 2, 4, 4, 6, 0, 6, 7, 4, 4, 5, 0,
        4, 4, 6, 9, 9, 6, 8, 3, 9, 5, 0, 9, 0, 4, 7, 2, 6, 1, 3, 7, 3, 8, 2, 4,
        3, 8, 6, 7, 4, 4, 6, 8, 2, 7, 8, 4, 4, 4, 8, 2])
tensor([3, 1, 1, 8, 4, 0, 3, 6, 9, 1, 6, 7, 1, 9, 1, 9, 7, 2, 1, 6, 8, 4, 1, 0,
        0, 8, 1, 0, 1, 0, 2, 4, 8, 2, 3, 8, 4, 3, 3,

In [13]:
import numpy as np 
import torch
from torch.utils.data import Dataset,DataLoader
import pandas as pd

(80000, 577)


In [128]:
### setting up the device
device = "cuda" if torch.cuda.is_available() else "cpu"

### creating an object of the class dataload
train_data = Data_load(data_file,L=24,device=device)

## creating a dataloader
train_dataloader = DataLoader(train_data,batch_size=100,shuffle=True)

for epoch in range(1):
    for (batch_idx,batch) in enumerate(train_dataloader):
        if batch_idx==1:
            print(batch['data'].shape)
        

torch.Size([100, 576])


### Loading and getting the data
* Dataload class (to load the data into {data,label}) dictionary
* One can use dataloader object as an iterator

In [116]:
x=np.arange(100)
y=[[j for i in range(10)] for j in range(10)]
y=np.array(y).flatten()
data = pd.DataFrame({'x':x,'y':y})
print(f'{data.head()}')
print(f'{data.tail()}')


   x  y
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0
     x  y
95  95  9
96  96  9
97  97  9
98  98  9
99  99  9


In [117]:
### class to load the data set 
### the output data can be 
class Dataload(Dataset):
    def __init__(self, data,device=device):
        self.x_data = torch.tensor(data.iloc[:,0].values,dtype=torch.float32).to(device=device)
        self.y_data = torch.tensor(data.iloc[:, 1].values, dtype=torch.float32).to(device=device)

    def __len__(self):
        return len(self.y_data)

    def __getitem__(self,idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        
        image = self.x_data[idx]
        label = self.y_data[idx]
        return {'data':image,'lab':label}

### creating a dataloader (iterator) and data set 

data_ld = Dataload(data)
tr_dloader = DataLoader(data_ld,batch_size=10,shuffle=True)
for epoch in range(1):
    for (batch_idx,batch) in enumerate(tr_dloader):
        print(batch['data'],batch['lab'])

tensor([25., 32.,  9., 63., 20., 17., 12., 30., 99., 46.]) tensor([2., 3., 0., 6., 2., 1., 1., 3., 9., 4.])
tensor([10., 44., 34., 28., 23., 74., 24., 65., 41., 60.]) tensor([1., 4., 3., 2., 2., 7., 2., 6., 4., 6.])
tensor([47., 84., 40., 51., 66., 31., 33., 39., 73., 36.]) tensor([4., 8., 4., 5., 6., 3., 3., 3., 7., 3.])
tensor([ 5., 96.,  8., 18., 52., 37., 78., 91., 49., 76.]) tensor([0., 9., 0., 1., 5., 3., 7., 9., 4., 7.])
tensor([87., 80., 72.,  7., 45., 85., 90.,  2., 86.,  1.]) tensor([8., 8., 7., 0., 4., 8., 9., 0., 8., 0.])
tensor([95., 14., 13.,  6., 93., 48., 75., 71., 35., 83.]) tensor([9., 1., 1., 0., 9., 4., 7., 7., 3., 8.])
tensor([98., 92., 38., 64., 55., 11.,  4., 68., 79., 57.]) tensor([9., 9., 3., 6., 5., 1., 0., 6., 7., 5.])
tensor([53., 56., 22., 15., 94., 70., 54., 58., 43., 69.]) tensor([5., 5., 2., 1., 9., 7., 5., 5., 4., 6.])
tensor([97., 27., 26., 67., 16., 77., 62.,  3.,  0., 21.]) tensor([9., 2., 2., 6., 1., 7., 6., 0., 0., 2.])
tensor([88., 81., 59., 29., 